# Generated by Django 3.2.9 on 2021-11-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('documentNumber', models.CharField(max_length=30)),
                ('issuedBy', models.CharField(max_length=100)),
                ('issuedDate', models.DateField()),
                ('IIN', models.CharField(max_length=12)),
                ('status', models.BooleanField()),
                ('frontDocument', models.ImageField(upload_to='photos')),
                ('backDocument', models.ImageField(upload_to='photos')),
                ('specs', models.CharField(max_length=100)),
            ],
        ),
    ]
