# Generated by Django 3.2.9 on 2021-11-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_receiver_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiver',
            name='backDocument',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='receiver',
            name='frontDocument',
            field=models.ImageField(upload_to=''),
        ),
    ]
