# Generated by Django 3.2.9 on 2021-11-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211122_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='receiver',
            field=models.CharField(default='Berik', max_length=100),
            preserve_default=False,
        ),
    ]
